// Generated by https://quicktype.io

export interface PokedexInterface {
  descriptions: Description[];
  id: number;
  is_main_series: boolean;
  name: string;
  names: any[];
  pokemon_entries: PokemonEntry[];
  region: null;
  version_groups: any[];
}

export interface Description {
  description?: string;
  language?: Language;
}

export interface Language {}

export interface PokemonEntry {
  entry_number: number;
  pokemon_species: PokemonSpecies;
}

export interface PokemonSpecies {
  name: string;
  url: string;
}
